version: '2'

services:
  postgres:
    build: ./database/
    container_name: 'sellpointapi_db'
    volumes: 
      - $PWD/data:/var/lib/postgresql/data
      - $PWD/database/init.sql:/docker-entrypoint-initdb.d/zinit.sql
  web:
    build: .
    hostname: "web"
    container_name: 'sellpointapi-src'
    working_dir: /home/app/library/
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    links:
      - postgres